#Estagio 1 - base
FROM mcr.microsoft.com/dotnet/aspnet:7.0 as base
RUN mkdir /app
WORKDIR /app
EXPOSE 80/tcp

#Estagio 2 - publish
FROM mcr.microsoft.com/dotnet/sdk as publish
WORKDIR /app
COPY mvc1.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o dist

#Estagio 3 - final
FROM base as final
WORKDIR /dist
COPY --from=publish /app/dist .
ENTRYPOINT ["dotnet","mvc1.dll"]